// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CancelActionApiActionsCancelActionIdDeleteData, CancelActionApiActionsCancelActionIdDeleteErrors, CancelActionApiActionsCancelActionIdDeleteResponses, ClearConversationHistoryApiChatHistorySessionIdDeleteData, ClearConversationHistoryApiChatHistorySessionIdDeleteErrors, ClearConversationHistoryApiChatHistorySessionIdDeleteResponses, ConfirmActionApiActionsConfirmActionIdPostData, ConfirmActionApiActionsConfirmActionIdPostErrors, ConfirmActionApiActionsConfirmActionIdPostResponses, CreateSessionApiChatSessionPostData, CreateSessionApiChatSessionPostResponses, ExecuteActionApiActionsExecutePostData, ExecuteActionApiActionsExecutePostErrors, ExecuteActionApiActionsExecutePostResponses, GetActionHistoryApiActionsHistoryGetData, GetActionHistoryApiActionsHistoryGetErrors, GetActionHistoryApiActionsHistoryGetResponses, GetActionResultApiActionsResultActionIdGetData, GetActionResultApiActionsResultActionIdGetErrors, GetActionResultApiActionsResultActionIdGetResponses, GetConfigInfoApiSettingsConfigGetData, GetConfigInfoApiSettingsConfigGetResponses, GetConversationHistoryApiChatHistorySessionIdGetData, GetConversationHistoryApiChatHistorySessionIdGetErrors, GetConversationHistoryApiChatHistorySessionIdGetResponses, GetPendingActionsApiActionsPendingGetData, GetPendingActionsApiActionsPendingGetResponses, HealthCheckHealthGetData, HealthCheckHealthGetResponses, ListSessionsApiChatSessionsGetData, ListSessionsApiChatSessionsGetResponses, RootGetData, RootGetResponses, SendMessageApiChatMessagePostData, SendMessageApiChatMessagePostErrors, SendMessageApiChatMessagePostResponses, SetApiKeyViaPromptApiSettingsApiKeyPostData, SetApiKeyViaPromptApiSettingsApiKeyPostErrors, SetApiKeyViaPromptApiSettingsApiKeyPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Send Message
 *
 * Send a message to the AI assistant and stream the response.
 * Uses Server-Sent Events (SSE) for real-time token streaming.
 *
 * Events:
 * - start: {"session_id": "..."} - Stream started
 * - token: {"content": "..."} - LLM token chunk
 * - done: {"content": "...", "session_id": "..."} - Complete response
 * - error: {"error": "...", "code": "...", "partial_content": "..."} - Error occurred
 */
export const sendMessageApiChatMessagePost = <ThrowOnError extends boolean = false>(options: Options<SendMessageApiChatMessagePostData, ThrowOnError>) => {
    return (options.client ?? client).post<SendMessageApiChatMessagePostResponses, SendMessageApiChatMessagePostErrors, ThrowOnError>({
        url: '/api/chat/message',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Clear Conversation History
 *
 * Clear conversation history for a session
 */
export const clearConversationHistoryApiChatHistorySessionIdDelete = <ThrowOnError extends boolean = false>(options: Options<ClearConversationHistoryApiChatHistorySessionIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<ClearConversationHistoryApiChatHistorySessionIdDeleteResponses, ClearConversationHistoryApiChatHistorySessionIdDeleteErrors, ThrowOnError>({
        url: '/api/chat/history/{session_id}',
        ...options
    });
};

/**
 * Get Conversation History
 *
 * Get conversation history for a session
 */
export const getConversationHistoryApiChatHistorySessionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetConversationHistoryApiChatHistorySessionIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetConversationHistoryApiChatHistorySessionIdGetResponses, GetConversationHistoryApiChatHistorySessionIdGetErrors, ThrowOnError>({
        url: '/api/chat/history/{session_id}',
        ...options
    });
};

/**
 * Create Session
 *
 * Create a new chat session
 * Note: Uses single thread per user (app_technical.md)
 */
export const createSessionApiChatSessionPost = <ThrowOnError extends boolean = false>(options?: Options<CreateSessionApiChatSessionPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<CreateSessionApiChatSessionPostResponses, unknown, ThrowOnError>({
        url: '/api/chat/session',
        ...options
    });
};

/**
 * List Sessions
 *
 * List all active sessions
 */
export const listSessionsApiChatSessionsGet = <ThrowOnError extends boolean = false>(options?: Options<ListSessionsApiChatSessionsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSessionsApiChatSessionsGetResponses, unknown, ThrowOnError>({
        url: '/api/chat/sessions',
        ...options
    });
};

/**
 * Execute Action
 *
 * Request execution of an action
 */
export const executeActionApiActionsExecutePost = <ThrowOnError extends boolean = false>(options: Options<ExecuteActionApiActionsExecutePostData, ThrowOnError>) => {
    return (options.client ?? client).post<ExecuteActionApiActionsExecutePostResponses, ExecuteActionApiActionsExecutePostErrors, ThrowOnError>({
        url: '/api/actions/execute',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Pending Actions
 *
 * Get list of actions pending confirmation
 */
export const getPendingActionsApiActionsPendingGet = <ThrowOnError extends boolean = false>(options?: Options<GetPendingActionsApiActionsPendingGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPendingActionsApiActionsPendingGetResponses, unknown, ThrowOnError>({
        url: '/api/actions/pending',
        ...options
    });
};

/**
 * Confirm Action
 *
 * Confirm and execute a pending action
 */
export const confirmActionApiActionsConfirmActionIdPost = <ThrowOnError extends boolean = false>(options: Options<ConfirmActionApiActionsConfirmActionIdPostData, ThrowOnError>) => {
    return (options.client ?? client).post<ConfirmActionApiActionsConfirmActionIdPostResponses, ConfirmActionApiActionsConfirmActionIdPostErrors, ThrowOnError>({
        url: '/api/actions/confirm/{action_id}',
        ...options
    });
};

/**
 * Cancel Action
 *
 * Cancel a pending action
 */
export const cancelActionApiActionsCancelActionIdDelete = <ThrowOnError extends boolean = false>(options: Options<CancelActionApiActionsCancelActionIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<CancelActionApiActionsCancelActionIdDeleteResponses, CancelActionApiActionsCancelActionIdDeleteErrors, ThrowOnError>({
        url: '/api/actions/cancel/{action_id}',
        ...options
    });
};

/**
 * Get Action Result
 *
 * Get the result of an action
 */
export const getActionResultApiActionsResultActionIdGet = <ThrowOnError extends boolean = false>(options: Options<GetActionResultApiActionsResultActionIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetActionResultApiActionsResultActionIdGetResponses, GetActionResultApiActionsResultActionIdGetErrors, ThrowOnError>({
        url: '/api/actions/result/{action_id}',
        ...options
    });
};

/**
 * Get Action History
 *
 * Get history of executed actions
 */
export const getActionHistoryApiActionsHistoryGet = <ThrowOnError extends boolean = false>(options?: Options<GetActionHistoryApiActionsHistoryGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetActionHistoryApiActionsHistoryGetResponses, GetActionHistoryApiActionsHistoryGetErrors, ThrowOnError>({
        url: '/api/actions/history',
        ...options
    });
};

/**
 * Get Config Info
 *
 * Return basic configuration details for the app.
 */
export const getConfigInfoApiSettingsConfigGet = <ThrowOnError extends boolean = false>(options?: Options<GetConfigInfoApiSettingsConfigGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetConfigInfoApiSettingsConfigGetResponses, unknown, ThrowOnError>({
        url: '/api/settings/config',
        ...options
    });
};

/**
 * Set Api Key Via Prompt
 *
 * Prompt the user for an API key via pynentry and save it to keyring.
 */
export const setApiKeyViaPromptApiSettingsApiKeyPost = <ThrowOnError extends boolean = false>(options: Options<SetApiKeyViaPromptApiSettingsApiKeyPostData, ThrowOnError>) => {
    return (options.client ?? client).post<SetApiKeyViaPromptApiSettingsApiKeyPostResponses, SetApiKeyViaPromptApiSettingsApiKeyPostErrors, ThrowOnError>({
        url: '/api/settings/api-key',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Health Check
 */
export const healthCheckHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckHealthGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<HealthCheckHealthGetResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Root
 */
export const rootGet = <ThrowOnError extends boolean = false>(options?: Options<RootGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<RootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};
