// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * ActionConfirmation
 *
 * Action confirmation request
 */
export type ActionConfirmation = {
    /**
     * Action Id
     */
    action_id: string;
    action_type: ActionType;
    /**
     * Description
     */
    description: string;
    /**
     * Parameters
     */
    parameters: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * ActionRequest
 *
 * Request to execute an action
 */
export type ActionRequest = {
    action_type: ActionType;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: unknown;
    };
    /**
     * Description
     *
     * Human-readable description of the action
     */
    description: string;
    /**
     * Requires Confirmation
     *
     * Whether user confirmation is required
     */
    requires_confirmation?: boolean;
    /**
     * Session Id
     */
    session_id?: string | null;
};

/**
 * ActionResult
 *
 * Result of an action execution
 */
export type ActionResult = {
    /**
     * Action Id
     */
    action_id: string;
    action_type: ActionType;
    /**
     * Status
     */
    status: string;
    /**
     * Result
     */
    result?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Executed At
     */
    executed_at?: string | null;
};

/**
 * ActionType
 *
 * Available action types
 */
export type ActionType = 'mock' | 'reminder' | 'note' | 'search';

/**
 * ChatMessage
 *
 * Chat message model
 */
export type ChatMessage = {
    /**
     * Content
     */
    content: string;
    /**
     * Role
     */
    role?: string;
    /**
     * Timestamp
     */
    timestamp?: string | null;
    /**
     * Session Id
     *
     * Optional session ID
     */
    session_id?: string | null;
    /**
     * Name
     *
     * Name of the speaker
     */
    name?: string | null;
};

/**
 * ChatResponse
 *
 * Chat response model
 */
export type ChatResponse = {
    /**
     * Content
     */
    content: string;
    /**
     * Role
     */
    role?: string;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Requires Action
     */
    requires_action?: boolean;
    /**
     * Action Data
     */
    action_data?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ConversationHistory
 *
 * Conversation history model
 */
export type ConversationHistory = {
    /**
     * Messages
     */
    messages: Array<ChatMessage>;
    /**
     * Session Id
     */
    session_id: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NotificationConfig
 *
 * Complete notification configuration
 */
export type NotificationConfig = {
    /**
     * Notifications
     */
    notifications: Array<NotificationType>;
};

/**
 * NotificationStatus
 *
 * Status of notification preparation
 */
export type NotificationStatus = {
    /**
     * Last Preparation
     */
    last_preparation: string | null;
    /**
     * Next Preparation
     */
    next_preparation: string;
    /**
     * Notifications Scheduled
     */
    notifications_scheduled: number;
    /**
     * Status
     */
    status: string;
};

/**
 * NotificationType
 *
 * Configuration for a notification type
 */
export type NotificationType = {
    /**
     * Name
     */
    name: string;
    /**
     * Time
     */
    time: string | Array<string>;
    /**
     * Frequency
     */
    frequency?: number;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * ScheduledNotification
 *
 * A scheduled notification
 */
export type ScheduledNotification = {
    /**
     * Notification Id
     */
    notification_id: string;
    /**
     * Scheduled Time
     */
    scheduled_time: string;
    /**
     * Notification Type
     */
    notification_type: string;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Status
     */
    status?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type SendMessageApiChatMessagePostData = {
    body: ChatMessage;
    path?: never;
    query?: never;
    url: '/api/chat/message';
};

export type SendMessageApiChatMessagePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageApiChatMessagePostError = SendMessageApiChatMessagePostErrors[keyof SendMessageApiChatMessagePostErrors];

export type SendMessageApiChatMessagePostResponses = {
    /**
     * Successful Response
     */
    200: ChatResponse;
};

export type SendMessageApiChatMessagePostResponse = SendMessageApiChatMessagePostResponses[keyof SendMessageApiChatMessagePostResponses];

export type ClearConversationHistoryApiChatHistorySessionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/api/chat/history/{session_id}';
};

export type ClearConversationHistoryApiChatHistorySessionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ClearConversationHistoryApiChatHistorySessionIdDeleteError = ClearConversationHistoryApiChatHistorySessionIdDeleteErrors[keyof ClearConversationHistoryApiChatHistorySessionIdDeleteErrors];

export type ClearConversationHistoryApiChatHistorySessionIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetConversationHistoryApiChatHistorySessionIdGetData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/chat/history/{session_id}';
};

export type GetConversationHistoryApiChatHistorySessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConversationHistoryApiChatHistorySessionIdGetError = GetConversationHistoryApiChatHistorySessionIdGetErrors[keyof GetConversationHistoryApiChatHistorySessionIdGetErrors];

export type GetConversationHistoryApiChatHistorySessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationHistory;
};

export type GetConversationHistoryApiChatHistorySessionIdGetResponse = GetConversationHistoryApiChatHistorySessionIdGetResponses[keyof GetConversationHistoryApiChatHistorySessionIdGetResponses];

export type CreateSessionApiChatSessionPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/session';
};

export type CreateSessionApiChatSessionPostResponses = {
    /**
     * Response Create Session Api Chat Session Post
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CreateSessionApiChatSessionPostResponse = CreateSessionApiChatSessionPostResponses[keyof CreateSessionApiChatSessionPostResponses];

export type ListSessionsApiChatSessionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/chat/sessions';
};

export type ListSessionsApiChatSessionsGetResponses = {
    /**
     * Response List Sessions Api Chat Sessions Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListSessionsApiChatSessionsGetResponse = ListSessionsApiChatSessionsGetResponses[keyof ListSessionsApiChatSessionsGetResponses];

export type GetNotificationConfigApiNotificationsConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/config';
};

export type GetNotificationConfigApiNotificationsConfigGetResponses = {
    /**
     * Successful Response
     */
    200: NotificationConfig;
};

export type GetNotificationConfigApiNotificationsConfigGetResponse = GetNotificationConfigApiNotificationsConfigGetResponses[keyof GetNotificationConfigApiNotificationsConfigGetResponses];

export type UpdateNotificationConfigApiNotificationsConfigPostData = {
    body: NotificationConfig;
    path?: never;
    query?: never;
    url: '/api/notifications/config';
};

export type UpdateNotificationConfigApiNotificationsConfigPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateNotificationConfigApiNotificationsConfigPostError = UpdateNotificationConfigApiNotificationsConfigPostErrors[keyof UpdateNotificationConfigApiNotificationsConfigPostErrors];

export type UpdateNotificationConfigApiNotificationsConfigPostResponses = {
    /**
     * Response Update Notification Config Api Notifications Config Post
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type UpdateNotificationConfigApiNotificationsConfigPostResponse = UpdateNotificationConfigApiNotificationsConfigPostResponses[keyof UpdateNotificationConfigApiNotificationsConfigPostResponses];

export type PrepareNotificationsApiNotificationsPreparePostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/prepare';
};

export type PrepareNotificationsApiNotificationsPreparePostResponses = {
    /**
     * Successful Response
     */
    200: NotificationStatus;
};

export type PrepareNotificationsApiNotificationsPreparePostResponse = PrepareNotificationsApiNotificationsPreparePostResponses[keyof PrepareNotificationsApiNotificationsPreparePostResponses];

export type GetScheduledNotificationsApiNotificationsScheduledGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/scheduled';
};

export type GetScheduledNotificationsApiNotificationsScheduledGetResponses = {
    /**
     * Response Get Scheduled Notifications Api Notifications Scheduled Get
     *
     * Successful Response
     */
    200: Array<ScheduledNotification>;
};

export type GetScheduledNotificationsApiNotificationsScheduledGetResponse = GetScheduledNotificationsApiNotificationsScheduledGetResponses[keyof GetScheduledNotificationsApiNotificationsScheduledGetResponses];

export type CancelNotificationApiNotificationsScheduledNotificationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Notification Id
         */
        notification_id: string;
    };
    query?: never;
    url: '/api/notifications/scheduled/{notification_id}';
};

export type CancelNotificationApiNotificationsScheduledNotificationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelNotificationApiNotificationsScheduledNotificationIdDeleteError = CancelNotificationApiNotificationsScheduledNotificationIdDeleteErrors[keyof CancelNotificationApiNotificationsScheduledNotificationIdDeleteErrors];

export type CancelNotificationApiNotificationsScheduledNotificationIdDeleteResponses = {
    /**
     * Response Cancel Notification Api Notifications Scheduled  Notification Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CancelNotificationApiNotificationsScheduledNotificationIdDeleteResponse = CancelNotificationApiNotificationsScheduledNotificationIdDeleteResponses[keyof CancelNotificationApiNotificationsScheduledNotificationIdDeleteResponses];

export type TestNotificationApiNotificationsTestPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/notifications/test';
};

export type TestNotificationApiNotificationsTestPostResponses = {
    /**
     * Response Test Notification Api Notifications Test Post
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type TestNotificationApiNotificationsTestPostResponse = TestNotificationApiNotificationsTestPostResponses[keyof TestNotificationApiNotificationsTestPostResponses];

export type ExecuteActionApiActionsExecutePostData = {
    body: ActionRequest;
    path?: never;
    query?: never;
    url: '/api/actions/execute';
};

export type ExecuteActionApiActionsExecutePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteActionApiActionsExecutePostError = ExecuteActionApiActionsExecutePostErrors[keyof ExecuteActionApiActionsExecutePostErrors];

export type ExecuteActionApiActionsExecutePostResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type ExecuteActionApiActionsExecutePostResponse = ExecuteActionApiActionsExecutePostResponses[keyof ExecuteActionApiActionsExecutePostResponses];

export type GetPendingActionsApiActionsPendingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/actions/pending';
};

export type GetPendingActionsApiActionsPendingGetResponses = {
    /**
     * Response Get Pending Actions Api Actions Pending Get
     *
     * Successful Response
     */
    200: Array<ActionConfirmation>;
};

export type GetPendingActionsApiActionsPendingGetResponse = GetPendingActionsApiActionsPendingGetResponses[keyof GetPendingActionsApiActionsPendingGetResponses];

export type ConfirmActionApiActionsConfirmActionIdPostData = {
    body?: never;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/actions/confirm/{action_id}';
};

export type ConfirmActionApiActionsConfirmActionIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ConfirmActionApiActionsConfirmActionIdPostError = ConfirmActionApiActionsConfirmActionIdPostErrors[keyof ConfirmActionApiActionsConfirmActionIdPostErrors];

export type ConfirmActionApiActionsConfirmActionIdPostResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type ConfirmActionApiActionsConfirmActionIdPostResponse = ConfirmActionApiActionsConfirmActionIdPostResponses[keyof ConfirmActionApiActionsConfirmActionIdPostResponses];

export type CancelActionApiActionsCancelActionIdDeleteData = {
    body?: never;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/actions/cancel/{action_id}';
};

export type CancelActionApiActionsCancelActionIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelActionApiActionsCancelActionIdDeleteError = CancelActionApiActionsCancelActionIdDeleteErrors[keyof CancelActionApiActionsCancelActionIdDeleteErrors];

export type CancelActionApiActionsCancelActionIdDeleteResponses = {
    /**
     * Response Cancel Action Api Actions Cancel  Action Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type CancelActionApiActionsCancelActionIdDeleteResponse = CancelActionApiActionsCancelActionIdDeleteResponses[keyof CancelActionApiActionsCancelActionIdDeleteResponses];

export type GetActionResultApiActionsResultActionIdGetData = {
    body?: never;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/actions/result/{action_id}';
};

export type GetActionResultApiActionsResultActionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActionResultApiActionsResultActionIdGetError = GetActionResultApiActionsResultActionIdGetErrors[keyof GetActionResultApiActionsResultActionIdGetErrors];

export type GetActionResultApiActionsResultActionIdGetResponses = {
    /**
     * Successful Response
     */
    200: ActionResult;
};

export type GetActionResultApiActionsResultActionIdGetResponse = GetActionResultApiActionsResultActionIdGetResponses[keyof GetActionResultApiActionsResultActionIdGetResponses];

export type GetActionHistoryApiActionsHistoryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/actions/history';
};

export type GetActionHistoryApiActionsHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActionHistoryApiActionsHistoryGetError = GetActionHistoryApiActionsHistoryGetErrors[keyof GetActionHistoryApiActionsHistoryGetErrors];

export type GetActionHistoryApiActionsHistoryGetResponses = {
    /**
     * Response Get Action History Api Actions History Get
     *
     * Successful Response
     */
    200: Array<ActionResult>;
};

export type GetActionHistoryApiActionsHistoryGetResponse = GetActionHistoryApiActionsHistoryGetResponses[keyof GetActionHistoryApiActionsHistoryGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
